### ISSUE TITLE
npm run fails

### ISSUE THREAD

**Issue by ChrisVilches** [markmur/sails-react-webpack#5]
Seems like a weird error running `npm start`

```
> sails-react-webpack@0.2.0 start C:\Users\Felo\Desktop\sailsreactwebpack
> nf start --wrap

[WARN] No ENV file found
[OKAY] Wrapping display Output to NaN Columns
C:\Users\Felo\Desktop\sailsreactwebpack\node_modules\foreman\lib\console.js:11
    return wrap(log.substr(length), length, res);
                    ^

RangeError: Maximum call stack size exceeded
    at String.substr (native)
    at wrap (C:\Users\Felo\Desktop\sailsreactwebpack\node_modules\foreman\lib\console.js:11:21)
    at wrap (C:\Users\Felo\Desktop\sailsreactwebpack\node_modules\foreman\lib\console.js:11:12)
    at wrap (C:\Users\Felo\Desktop\sailsreactwebpack\node_modules\foreman\lib\console.js:11:12)
    at wrap (C:\Users\Felo\Desktop\sailsreactwebpack\node_modules\foreman\lib\console.js:11:12)
    at wrap (C:\Users\Felo\Desktop\sailsreactwebpack\node_modules\foreman\lib\console.js:11:12)
    at wrap (C:\Users\Felo\Desktop\sailsreactwebpack\node_modules\foreman\lib\console.js:11:12)
    at wrap (C:\Users\Felo\Desktop\sailsreactwebpack\node_modules\foreman\lib\console.js:11:12)
    at wrap (C:\Users\Felo\Desktop\sailsreactwebpack\node_modules\foreman\lib\console.js:11:12)
    at wrap (C:\Users\Felo\Desktop\sailsreactwebpack\node_modules\foreman\lib\console.js:11:12)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sails-react-webpack@0.2.0 start: `nf start --wrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sails-react-webpack@0.2.0 start script 'nf start --wrap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sails-react-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nf start --wrap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sails-react-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sails-react-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Felo\Desktop\sailsreactwebpack\npm-debug.log
```

And `debug.log` is:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle sails-react-webpack@0.2.0~prestart: sails-react-webpack@0.2.0
6 silly lifecycle sails-react-webpack@0.2.0~prestart: no script for prestart, continuing
7 info lifecycle sails-react-webpack@0.2.0~start: sails-react-webpack@0.2.0
8 verbose lifecycle sails-react-webpack@0.2.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle sails-react-webpack@0.2.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Felo\Desktop\sailsreactwebpack\node_modules\.bin;C:\Users\Felo\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Felo\bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\app\Felo\product\12.1.0\dbhome_1\bin;C:\Program Files\Java\jdk1.8.0_121\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;D:\Programming\myPathPrograms\win;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\doxygen\bin;C:\MinGW\bin;C:\Program Files\nodejs;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Git\cmd;C:\Program Files (x86)\Android SDK\tools;C:\Program Files (x86)\Android SDK\platform-tools;C:\ProgramData\chocolatey\bin;C:\Users\Felo\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.1;C:\MinGW\bin;C:\MinGW\bin;C:\Users\Felo\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle sails-react-webpack@0.2.0~start: CWD: C:\Users\Felo\Desktop\sailsreactwebpack
11 silly lifecycle sails-react-webpack@0.2.0~start: Args: [ '/d /s /c', 'nf start --wrap' ]
12 silly lifecycle sails-react-webpack@0.2.0~start: Returned: code: 1  signal: null
13 info lifecycle sails-react-webpack@0.2.0~start: Failed to exec start script
14 verbose stack Error: sails-react-webpack@0.2.0 start: `nf start --wrap`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid sails-react-webpack@0.2.0
16 verbose cwd C:\Users\Felo\Desktop\sailsreactwebpack
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error sails-react-webpack@0.2.0 start: `nf start --wrap`
22 error Exit status 1
23 error Failed at the sails-react-webpack@0.2.0 start script 'nf start --wrap'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the sails-react-webpack package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     nf start --wrap
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs sails-react-webpack
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls sails-react-webpack
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by markmur** [comment]
@FeloVilches do you get the error without the `--wrap` argument. i.e `nf start`?

**Comment by stokesbga** [comment]
did you yarn

**Comment by markmur** [comment]
Closing as there has been no response for 20 days. Feel free to reopen if you have additional info to add.

**Comment by xolan** [comment]
Getting the same error:

```
sails_1  | > sails-react-webpack@0.2.0 start /server
sails_1  | > nf start --wrap
sails_1  | 
sails_1  | [WARN] No ENV file found
sails_1  | [OKAY] Wrapping display Output to NaN Columns
sails_1  | /server/node_modules/foreman/lib/console.js:16
sails_1  |     return wrap(log.substr(length), length, res);
sails_1  |                     ^
sails_1  | 
sails_1  | RangeError: Maximum call stack size exceeded
sails_1  |     at wrap (/server/node_modules/foreman/lib/console.js:16:21)
sails_1  |     at wrap (/server/node_modules/foreman/lib/console.js:16:12)
sails_1  |     at wrap (/server/node_modules/foreman/lib/console.js:16:12)
sails_1  |     at wrap (/server/node_modules/foreman/lib/console.js:16:12)
sails_1  |     at wrap (/server/node_modules/foreman/lib/console.js:16:12)
sails_1  |     at wrap (/server/node_modules/foreman/lib/console.js:16:12)
sails_1  |     at wrap (/server/node_modules/foreman/lib/console.js:16:12)
sails_1  |     at wrap (/server/node_modules/foreman/lib/console.js:16:12)
sails_1  |     at wrap (/server/node_modules/foreman/lib/console.js:16:12)
sails_1  |     at wrap (/server/node_modules/foreman/lib/console.js:16:12)
```

Removing `--wrap` fixes the issue.

I'm running docker. Also had to upgrade `foreman` to `>=2.0.0` and change `webpackDevServer.js` to listen on `0.0.0.0`.
